# Generated by Django 4.1.7 on 2023-02-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GST',
            fields=[
                ('gst_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hsn_code', models.CharField(max_length=8, unique=True)),
                ('cgst', models.IntegerField(default=0)),
                ('sgst', models.IntegerField(default=0)),
                ('igst', models.IntegerField(default=0)),
                ('discription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=30)),
                ('offer_in_percentile', models.FloatField(default=0)),
                ('offer_in_rupees', models.FloatField(default=0)),
                ('offer_start_date', models.DateField()),
                ('offer_end_date', models.DateField()),
                ('offer_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('catogery_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_cost_per_quantity', models.FloatField()),
                ('product_cost_with_gst', models.FloatField(default=0)),
                ('product_quantity', models.FloatField(default=0)),
                ('product_total_cost', models.FloatField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='stocks_app.productcategory')),
                ('product_gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_products', to='stocks_app.gst')),
                ('product_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_products', to='stocks_app.offer')),
            ],
        ),
    ]
