# Generated by Django 4.1.7 on 2023-02-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0002_alter_product_product_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='stocks_app.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_gst',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_products', to='stocks_app.gst'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_products', to='stocks_app.offer'),
        ),
    ]
